# Generated by Django 5.2.17 on 2026-09-04 05:04

import django.db.models.deletion
import meetings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('avatar_color', models.CharField(default='#1a73e8', max_length=10)),
                ('status', models.CharField(default='Disponible', max_length=30)),
                ('last_call', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contacto de Llamadas',
                'verbose_name_plural': 'Contactos de Llamadas',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Reunión de videollamada', max_length=200)),
                ('code', models.CharField(db_index=True, default=meetings.models.generate_meeting_code, max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_instant', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_vpn', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reunión',
                'verbose_name_plural': 'Reuniones',
                'ordering': ['scheduled_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=20)),
                ('is_audio_muted', models.BooleanField(default=False)),
                ('is_video_muted', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Solicitud de Conexión',
                'verbose_name_plural': 'Solicitudes de Conexión',
                'ordering': ['requested_at'],
            },
        ),
    ]
